name: Backup

on: [push]

# on:
#   schedule:
#     - cron: "*/5 * * * *"

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Postgres
        uses: ankane/setup-postgres@v1
        with:
          postgres-version: 16

      - name: Backup
        run: |
          pg_dump postgres://postgres.${{ secrets.DEV_SUPABASE_REFERENCE_ID }}:${{ secrets.DEV_SUPABASE_PASSWORD }}@aws-0-sa-east-1.pooler.supabase.com:6543/postgres --format=c > backup.dump
          echo "Backup created at $(date)"

      - name: Upload a file to Google Drive
        uses: willo32/google-drive-upload-action@v1
        with:
          target: ./backup.dump
          credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
          parent_folder_id: backup_supabase
          name: $(date +'%Y-%m-%d').dump
